### ISSUE TITLE
Correct way of indicating exception being thrown in sequence diagram?

### ISSUE THREAD

**Issue by Exeexe93** [nus-cs2103-AY1920S2/forum#104]
In my sequence diagram, I have one portion whereby I would required to check the validation of the input. However, when it does not met any of those condition, it would required to throws exception. How should I indicate when exception is thrown in sequence diagram?

I have search through the internet and found out the following methods to indicate exception in sequence diagram:

Using alt loop:
![image](https://user-images.githubusercontent.com/42311220/78737089-4bf04100-7981-11ea-9696-bf960a9b04a6.png)

Using break:
![image](https://user-images.githubusercontent.com/42311220/78737134-63c7c500-7981-11ea-966c-6b76c84d9551.png)
[Source](https://johanvergeer.github.io/posts/uml-sequence-diagram-exception-handling)

Which of the following is correct to follow?

Please advise! Thanks!

**Comment by okkhoy** [comment]
It turns out there is no standard way to represent exceptions in SD. There is something for state diagrams, which is not covered in this module.

So you are free to use either one. 

You can indicate that you are representing exception using UML Notes.

**Comment by Exeexe93** [comment]
Thanks Prof for clarifying.
