### ISSUE TITLE
Use of levenshtein distance library

### ISSUE THREAD

**Issue by BransonNg** [nus-cs2103-AY1920S2/forum#107]
Also Prof, am hoping to not add it as a dependency, as I only need this one file and my team's JAR is becoming pretty big. Thank you in advance!

## Library

[org.apache.commons.text.similarity] 
(http://commons.apache.org/sandbox/commons-text/jacoco/org.apache.commons.text.similarity/LevenshteinDistance.java.html)

## Purpose

Calculation of edit distance for find command. 

## License
Apache Licence Version 2
http://www.apache.org/licenses/LICENSE-2.0

**Comment by BransonNg** [comment]
And if this is allowed, how should I go about acknowledging the owner? Could I just insert the link as a comment to the snippet referenced?

Thank you.

**Comment by okkhoy** [comment]
Copy-paste the file as it is (what about its dependencies, if any?) and retain the license note on top. 
In your ack segment in the doc mention it. No one in the team can claim credit for  this file, so mark it with @@author-reused tag

**Comment by BransonNg** [comment]
okay, sure! the file is independent.
Ack segment in DG?
how do i mark the file with the tag? is it inline? or somehow via github?

**Comment by okkhoy** [comment]
> how do i mark the file with the tag? is it inline? or some ...

Check the section on making code reposense compatible in the website. It has instructions

**Comment by BransonNg** [comment]
Found it, thank you!
