### ISSUE TITLE
Multiplicity and Dependency

### ISSUE THREAD

**Issue by eugenetyc** [nus-cs2103-AY1920S2/forum#109]
Hi guys, can multiplicity be used with dependency in the UML diagrams?
![image](https://user-images.githubusercontent.com/40591060/78978196-f0be7a00-7b4b-11ea-9798-427735c7d3d0.png)

Seen here, JsonSerializableFoodRecord has a List<JsonAdaptedFood> in it. However, JsonAdaptedFood has no knowledge of JsonSerializableFoodRecord, other than the fact any number of them could be put into the List.
![image](https://user-images.githubusercontent.com/40591060/78978307-1f3c5500-7b4c-11ea-8cd6-696536e304d1.png)
![image](https://user-images.githubusercontent.com/40591060/78978339-2d8a7100-7b4c-11ea-8f0a-3e361b39a0ad.png)

In this case, would it be a JsonSerializableFoodRecord "1" ---> "*" JsonAdaptedFood association? Moreover, I have not encountered any instances of using multiplicity with dependency arrows. This makes me uneasy :/

Likewise, the case is similar for JsonAdaptedFood having a List<JsonAdaptedTag>. Any help is much appreciated!

**Comment by okkhoy** [comment]
> can multiplicity be used with dependency in the UML diagrams?

Probably not. 

Multiplicity in some sense means one object contains a reference to X number of another object (X being the multiplicity)

Dependency, on the other hand, doesn't maintain any "state", it is transient.

Your `JsonSerializableFoodRecord` is associated with an `ArrayList` object not `JsonAdaptedFood`.

I suspect dependency here is "depends on the type", unless you have another method that takes an object of `JsonAdaptedFood` as a parameter or returns a `JsonAdaptedFood` object

**Comment by eugenetyc** [comment]
Ahh, I see now. Thank you!

**Comment by eugenetyc** [comment]
After closing the issue, I reopened it upon encountering a thought.

If class A does have any attributes of class B, and does not take in class B as a parameter of its methods, but makes use of Class B in one of its methods, would it be correct to say that Class A has a dependency on Class B?

**Comment by okkhoy** [comment]
Eh? I am confused. I don't think I understood your question. 

What do you mean by: 
>If class A does have any attributes of class B

Do you have a variable of type Class B in Class A?

**Comment by eugenetyc** [comment]
Class A does not have any fields of the type Class B.
Class A only has a Method X that takes in Class C as parameter; Class C knows of Class B.

When Method X of Class A is called (with a Class C object as argument):
- Class C introduces objects of Class B in the running of this Method X, and works with them.
- Method X is a public void method. No instances of Class B are returned.

Would Class A have a dependency on Class B now?

**Comment by okkhoy** [comment]
Yes, in this case there is dependency between A and B.

However,

> Class A only has a Method X that takes in Class C as parameter; Class C knows of Class B.

Is bad design! Which principle is it violating?

**Comment by eugenetyc** [comment]
Law of Demeter?

**Comment by okkhoy** [comment]
Bingo!

**Comment by eugenetyc** [comment]
Ah, one of the principles I find most interesting and like to follow myself personally. Alright, thank you for the help!
