### ISSUE TITLE
Unable to log in to Catcher

### ISSUE THREAD

**Issue by shenghaoc** [nus-cs2103-AY1920S2/forum#131]
Does anyone know how to fix "Error: Invalid Record Length: header length is 3, got 1 on line 206"?

![Screenshot from 2020-04-18 11-14-07](https://user-images.githubusercontent.com/34920365/79626832-ee6ca900-8165-11ea-98f3-05c62874a09d.png)

**Comment by nelsontky** [comment]
Me too, my group has this problem too.

**Comment by joshlay96** [comment]
Am facing the same issue as well.

**Comment by nathanaelseen** [comment]
Me too

**Comment by PotatoCombat** [comment]
I believe the issue occurs when a team member has already logged in to Catcher.
I have a group member on Catcher at the moment, but I could not log in and neither could my other team members.

**Comment by raniceyue** [comment]
Having the same issue and I'm the only one logging into CATcher

**Comment by dargohzy** [comment]
Facing the same issue.

**Comment by dargohzy** [comment]
Severity: Very High

**Comment by okkhoy** [comment]
Please try now? the catcher team says issue is resolved

**Comment by shenghaoc** [comment]
Thank you @okkhoy and the CATcher team!
