### ISSUE TITLE
Assigning of persons to fix bug

### ISSUE THREAD

**Issue by seanlowcy77** [nus-cs2103-AY1920S2/forum#136]
Dear Profs / TA,

While the guide does say that penalty will be divided if there is no assignee - I was wondering does it imply that the penalty will be assigned to the assignee? 

Also, with regards to features that are a collective contribution from the team should we leave the assignee as blank?

In addition, assuming that penalty for the bugs will be given to the assigned team member, will it be a little unfair for team members who have contributed more features? - as they might potentially take on more bugs, due to the number of additional features they might have implemented.

Thank you!

![Screenshot 2020-04-19 at 11 51 18 AM](https://user-images.githubusercontent.com/52877163/79679003-4c67c200-8234-11ea-89d1-200dd1ea0496.png)

**Comment by shenghaoc** [comment]
Don't you also get more credit for implementing more features?

**Comment by okkhoy** [comment]
>  I was wondering does it imply that the penalty will be assigned to the assignee?

Yes

> ... that are a collective contribution from the team should we leave the assignee as blank

You can do that, automatically it will be distributed to the entire team.

> additional features => more bugs and related ...

Not really, we look at the [density, not pure numbers](https://nus-cs2103-ay1920s2.github.io/website/admin/tp-grading.html#grading-bugs-found-in-the-pe).

**Comment by seanlowcy77** [comment]
Ok sure thanks prof!
