### ISSUE TITLE
Issue still under "Issues Pending Response" when it has been responded to

### ISSUE THREAD

**Issue by huixianc** [nus-cs2103-AY1920S2/forum#137]
Hi, the boxed up issue has been responded to, but it is still listed under "Issues Pending Response"

![image](https://user-images.githubusercontent.com/50432304/79683207-ffe3ad00-825a-11ea-9e75-b77374a78770.png)

![image](https://user-images.githubusercontent.com/50432304/79683236-489b6600-825b-11ea-98f9-50eab02e7edb.png)

I have tried editing the response, but the issue is still stuck as pending

**Comment by okkhoy** [comment]
Try "sync" on top?

**Comment by huixianc** [comment]
> Try "sync" on top?

Hi prof, I have tried to sync but it still appears under "issues pending response"

there was also the following error 

![image](https://user-images.githubusercontent.com/50432304/79685156-0aa53e80-8269-11ea-914f-b414c34040ab.png)

**Comment by JunWei96** [comment]
Hi,

Apologies for the inconvenienced caused, a temporary workaround for this would be to manually go to the Github issue page and add the "Done" label. CATcher will automatically pick that up and mark it as done.

**Comment by huixianc** [comment]
> Hi,
> 
> Apologies for the inconvenienced caused, a temporary workaround for this would be to manually go to the Github issue page and add the "Done" label. CATcher will automatically pick that up and mark it as done.

hello, I am not sure if we are allowed to manually add the label? We have been instructed to use only CATcher and not to use the GitHub interface directly 

![image](https://user-images.githubusercontent.com/50432304/79685259-fe6db100-8269-11ea-9100-b751ed12dbf7.png)

**Comment by damithc** [comment]
@huixianc 
Prof Akshay will set it as 'done' manually. @okkhoy can help?

**Comment by okkhoy** [comment]
Done! @huixianc check please.

**Comment by huixianc** [comment]
> Done! @huixianc check please.

yup it's no longer under pending requests, thank you very much prof!
