### ISSUE TITLE
Tagging commit in branch instead tags commit in master

### ISSUE THREAD

**Issue by teo-jun-xiong** [nus-cs2103-AY1920S2/forum#15]
As per the Level-7 increment, I created branch-Level-7 and did some commits to it. Using Sourcetree, I tagged my latest commit in branch-Level-7 with Level-7 and pushed. However, on Github, Level-7 was tagged to a commit that was before I created that branch. 

![image](https://user-images.githubusercontent.com/50788391/73192946-cd974780-4164-11ea-8399-692048249606.png)

![image](https://user-images.githubusercontent.com/50788391/73193027-ea337f80-4164-11ea-9287-182274f4883f.png)

In the first image, I tagged Level-7 on the latest commit on branch-Level-7, yet on Github, Level-7 is tagged an old commit. Any idea why this is so? I did revert a commit in the master branch, could that be the reason?

Thanks!

**Comment by zhuhanming** [comment]
Hi @teo-jun-xiong, I'm not that familiar with Sourcetree, but perhaps there was some issue when Sourcetree pushed your tag to GitHub, where it tagged the latest commit (which is in master) before it pushed the branch.

I believe the instructions on the site asked us to merge the branch into master first before tagging it (on master). Regardless, I would recommend doing the following (on your CLI):
```
// Delete remote tag
git push origin :tagname

// Delete local tag
git tag --delete tagname
```
Subsequently, you can create the tag again. If you wish to tag a specific commit on some branch, make sure you [checkout](https://git-scm.com/docs/git-checkout) to that branch, use `git log` to find the SHA hash of the commit you wish to tag e.g. `15027957951b64cf874c3557a0f3547bd83b3ff6` then run the following command (while you're on that branch!):
```
// Example, replace v1.2 with tagname and the SHA has with your commit SHA hash
git tag -a v1.2 15027957951b64cf874c3557a0f3547bd83b3ff6
```
Then push again. For Level-7, you'd merge the branch into master, then probably tag the merge commit with Level-7, so you'd use the SHA hash of the merge commit.

EDIT: Referred to [stackoverflow](https://stackoverflow.com/a/5480292) and [atlassian](https://www.atlassian.com/git/tutorials/inspecting-a-repository/git-tag)

**Comment by eugenetyc** [comment]
Hi

You can right click in source tree that commit, and then click remove tag and select the one you want to remove.

Then you can just add the tag as usual again, and remember to push both tags and commits.

Cheers!

**Comment by teo-jun-xiong** [comment]
Thanks for the replies, I couldn't figure out the cause of my issue after trying out the suggestions. I've went ahead and followed @zhuhanming's suggestion, which was to merge the branch into master before tagging it.

Cheers
