### ISSUE TITLE
Permission denied when pushing to origin

### ISSUE THREAD

**Issue by xCelestialPhoenix** [nus-cs2103-AY1920S2/forum#2]
I got this error message on the console of intelliJ IDEA when I ran `git push origin A-Gradle`

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Before this I ran `git remote set-url origin git@github.com:xCelestialPhoenix/duke.git` because `git push` was requesting username and password for github.com and I read for [here](https://stackoverflow.com/questions/15495843/gitlab-git-user-password) that we should change the remote url from https to ssh.

I'm running IntelliJ community 2019.3 v11.0.4, Java JDK 11 on Windows.

P.S. If this is not crucial, I would prefer to just push my codes from IntelliJ and create the tags on GitHub.

**Comment by okkhoy** [comment]
You need to set up a key-pair before using the ssh method (ie., `git@github....`). Did you do that?

**Comment by xCelestialPhoenix** [comment]
Thank you for the tip. I went through the process and now it managed to work.
