### ISSUE TITLE
Is there a specific order for feature implementation

### ISSUE THREAD

**Issue by raniceyue** [nus-cs2103-AY1920S2/forum#21]
Edit: This question is about Week 3's IP assignment

Are we allowed to implement the features in Step 4 before proceeding to implement Level-7 onwards? Or is there no specific order we have to adhere to?

**Comment by okkhoy** [comment]
Technically - no harm.
From learning point of view, doing it in order gives you more opportunities to learn about organizing existing code better.
My suggestion: follow the order (apart from those that can be done in parallel, you can do either one first).
