### ISSUE TITLE
CheckStyle: Indentation for Array Initialisation

### ISSUE THREAD

**Issue by zhuhanming** [nus-cs2103-AY1920S2/forum#22]
Hi all, I'm currently facing this issue when initialising an array that is too long:
```
String[] folders = {"storageTestOne", "storageTestTwo", "storageTestThree",
        "storageTestFour", "storageTestSix"};
```
I am following the Java Coding Standards in terms of indentation as found [here](https://nus-cs2103-ay1920s2.github.io/website/coding-standards/java/intermediate.html#layout). It states that 
> **Indentation for wrapped lines should be 8 spaces** (i.e. twice the normal indentation of 4 spaces) more than the parent line.

However, the above indentation fails the CheckStyle test with the provided `checkstyle.xml`. It results in the following error:
```
[ant:checkstyle] [ERROR] .../StorageTest.java: 'array initialization' child has incorrect indentation level 16, expected level should be one of the following: 12, 28, 31. [Indentation]
```

It seems to be due to this in `checkstyle.xml`:
```
<module name="Indentation">
    // ...
   <property name="arrayInitIndent" value="4"/>
</module>
```
If I change the value to `"8"`, the error no longer occurs. 

I'd just like to ask, should I be changing the provided `checkstyle.xml` file, or should I change my indentation in my code instead (which means differing from the Coding Standards given)?

**Comment by mario7lorenzo** [comment]
Hi! I'm not sure whether checkstyle.xml modification is appropriate, but i have an alternative style for that issue:
<img width="234" alt="Screenshot 2020-01-31 at 1 19 13 PM" src="https://user-images.githubusercontent.com/43873384/73514355-64495a00-442c-11ea-92f5-1e7b04ad907b.png">

I don't get any checkstyle issue for this.

**Comment by zhuhanming** [comment]
Hi @mario7lorenzo, thanks for the response. I just gave it a try, but the same error occurs (except that it occurs five times instead now).

I'm not sure why you didn't get any checkstyle issue though - did you run `gradle checkstyleTest checkstyleMain` as well?

**Comment by mario7lorenzo** [comment]
yeah i'm running `./gradlew checkstyleMain checkstyleTest`. Wait let me try to figure out after the lecture hahah

------ UPDATE ------
As mentioned in the coding standard page:
`Use the Google Java Style Guide for any topics not covered in this document.`
So I refer to this website: [https://google.github.io/styleguide/javaguide.html#s4.8.3.1-array-initializers](url)

It is said that array initialization can be written in block format. Therefore, I decide to come up with the attached format.
<img width="243" alt="Screenshot 2020-01-31 at 3 26 02 PM" src="https://user-images.githubusercontent.com/43873384/73520187-0291eb80-443e-11ea-8453-39ece15b6954.png">

This one should both resolve the checkstyle issue and follows the desired coding style :)

**Comment by zhuhanming** [comment]
Thanks for your help @mario7lorenzo, for now I'm using the following workaround:
```
ArrayList<String> folders = new ArrayList<>(Arrays.asList("storageTestOne", "storageTestTwo",
        "storageTestThree", "storageTestFour", "storageTestSix"));
```
It somehow works if I'm declaring and initialising an ArrayList object instead.
