### ISSUE TITLE
Unable to load AnchorPane object from fxml file

### ISSUE THREAD

**Issue by CornCobs** [nus-cs2103-AY1920S2/forum#24]
Hi,

I followed the instructions from the javafx tutorial to create fxml files and controllers and whatnot. I have also updated the MainWindow.fxml file so the `fx:controller` property properly points to my MainWindow class (with package name, i.e. duke.MainWindow). However, when trying to run the application, on the following line:
```
AnchorPane ap = fxmlLoader.load();
```
I receive the following error: java.lang.NullPointerException: Input stream must not be null
I have tried debugging and am quite sure that `Main.class.getResource("/view/MainWindow.fxml")` is returning the correct URL, since I am able to read the file from the URL object in debug mode.

I have tried searching online but nothing comes up as well. Please advise!

**Comment by mario7lorenzo** [comment]
Hi, can I see the structure of your project directory? Because I have tried to move the `MainWindow` class to the `duke` package, but there is no issue if you change the `fx:controller` to `duke.MainWindow`

**Comment by CornCobs** [comment]
Hi Mario! I managed to solve the problem. It turns out it was my image resources that was causing the problem..

For anyone with some similar problem of loading the fxml file, do check the following:
1. Make sure the controller class in your fxml file uses the fully qualified name (eg. duke.MainWindow)
2. If using intellij try marking the resource folder as resource
3. Restart intellij
