### ISSUE TITLE
Error when running Launcher for Level-10, JavaFx GUI

### ISSUE THREAD

**Issue by gracegrape** [nus-cs2103-AY1920S2/forum#25]
Hello, after following the [JavaFx tutorial](https://github.com/nus-cs2103-AY1920S2/duke/blob/master/tutorials/javaFxTutorialPart1.md) using Gradle for level-10 (week4), I am unable to run my launcher class with the following error:
![image](https://user-images.githubusercontent.com/50510343/73586302-36285080-44e6-11ea-8382-99c67ee4c2b9.png)
---
![image](https://user-images.githubusercontent.com/50510343/73586306-4e986b00-44e6-11ea-8cf5-3d4ecec29ca5.png)
---
![image](https://user-images.githubusercontent.com/50510343/73586307-535d1f00-44e6-11ea-9c11-059719e73b14.png)

Here are my Duke class and Launcher class if needed, I have also updated my build.gradle as per the tutorial.
Duke:
![image](https://user-images.githubusercontent.com/50510343/73586352-e8601800-44e6-11ea-9e41-cf0f5ad748a2.png)
---
Launcher:
![image](https://user-images.githubusercontent.com/50510343/73586332-a20ab900-44e6-11ea-9f69-6d7a3fabc3bf.png)

Is there anything I can do regarding this error? Thanks in advance for any help!

**Comment by DANamic** [comment]
As the error points out, it's trying to launch the Duke class without passing anything during initialisation (in your case, your Duke expects `String filePath`). Either instantiate that with the Launcher or move the `String filePath` into the constructor itself, so that your method now looks like: `Duke() { your code here }` and try again.

**Comment by gracegrape** [comment]
> As the error points out, it's trying to launch the Duke class without passing anything during initialisation (in your case, your Duke expects `String filePath`). Either instantiate that with the Launcher or move the `String filePath` into the constructor itself, so that your method now looks like: `Duke() { your code here }` and try again.

Thank you so much! Fixed the error  :')
