### ISSUE TITLE
Gradle Test Fails

### ISSUE THREAD

**Issue by tianqi77** [nus-cs2103-AY1920S2/forum#33]
I'm trying to run the gradle command "test" in Intellij, but I keep getting errors. May I know how to solve it?

![Screenshot (40)](https://user-images.githubusercontent.com/42697036/73940406-5d3bb380-4926-11ea-9214-340fae86e605.png)
![Screenshot (41)](https://user-images.githubusercontent.com/42697036/73940410-5f057700-4926-11ea-8c08-f7e1235ae3dc.png)

**Comment by CornCobs** [comment]
We need details - what do you run in your tests? Are any of your tests possibly exiting the program (via System.exit or Platform.exit in javafx)? That would certainly cause stdin to be closed.

**Comment by mario7lorenzo** [comment]
Hi! May I know what you want to achieve? As in what commands you input to the terminal?

**Comment by tianqi77** [comment]
> We need details - what do you run in your tests? Are any of your tests possibly exiting the program (via System.exit or Platform.exit in javafx)? That would certainly cause stdin to be closed.

I only put some dummy test inside...like assertEquals(1,1)... I guess there is something wrong with my JUnit set up...

**Comment by tianqi77** [comment]
> Hi! May I know what you want to achieve? As in what commands you input to the terminal?

I put gradlew test...

**Comment by mario7lorenzo** [comment]
Hmm yea i think the most probable issue is in your JUnit setup. Try to refer back to the tutorial first, then try to follow the steps again.

**Comment by tianqi77** [comment]
I think the issue is with my jdk version. I used 12 instead of 11. The problem is resolved after I changed the version :D
