### ISSUE TITLE
iP week 5 task: Add Increments as PRs: A-Assertions, A-CodeQuality, A-Lambdas, A-Streams

### ISSUE THREAD

**Issue by lohszeying** [nus-cs2103-AY1920S2/forum#34]
Hi, what does `Add Increments as PRs: A-Assertions, A-CodeQuality, A-Lambdas, A-Streams` mean? Does that mean to go to the github under nus-cs2103-AY1920S2 and create a new pull request (similar to how we did Duke Increment PR)?

**Comment by mario7lorenzo** [comment]
Hi! What I did was, I created new branches for each of the feature. Then, for each one of them, I created a pull request, before merging them to my master branch.

**Comment by lohszeying** [comment]
> Hi! What I did was, I created new branches for each of the feature. Then, for each one of them, I created a pull request, before merging them to my master branch.

Hi, so after creating branch, then you create pull request from your own duke repo, and then work on the increment? Or do you work on the increment first (within the newly created branch), and then create pull request?

**Comment by lharland** [comment]
I believe there has to be something on the branch (worked on the features) before u create the pull request

**Comment by zhuhanming** [comment]
Hi @lohszeying, the increments should be done as branches on your fork, then merged into your master as per what we did for the past few weeks. The pull request should be done after you have made the changes on the branch. Of course, you can still make changes even after making the pull request (but before merging), these new commits will simply "stack" onto your existing pull request. Your pull request will automatically update to be from the latest commit on that branch.

I clarified with Prof Akshay earlier, you should be making the PR to your forked master, not to the nus-cs2103-AY1920S2 upstream repo.

**Comment by okkhoy** [comment]
>> The increments should be done as branches on your fork, then merged into your master as per what we did for the past few weeks. The pull request should be done after you have made the changes on the branch. 

This is correct.

**Comment by AaronCQL** [comment]
Hi Prof @okkhoy, to clarify what you mean, we should:

1. Create a branch and work on the increment
2. When we are satisfied, create a pull request to **our own** forked master to merge said branch 

In other words, we do not merge the branches using our local git CLI like last week and do not need to create any pull requests to the upstream repo?

**Comment by okkhoy** [comment]
@AaronCQL yes your understanding is correct. The idea is to get you used to managing pull requests on GitHub.

**Comment by agnesnatasya** [comment]
I followed the instructions on the module website on creating a pull request to our own branches, from A-Assertions, for example, to the master branch. But I do not know what to do after this. 
<img width="1217" alt="Screenshot 2020-02-09 at 7 12 22 PM" src="https://user-images.githubusercontent.com/44172431/74101046-864f8480-4b70-11ea-83fc-03ec7376607e.png">
They only show the changes between the 2 files, but how do I create the pull request?

Thank you!

**Comment by okkhoy** [comment]
don't you get this interface? (with a create pull request button)
![image](https://user-images.githubusercontent.com/1023494/74103777-ed2d6780-4b89-11ea-9314-45c47aeef900.png)

others, is your experience the same?

**Comment by agnesnatasya** [comment]
Hi Prof, yes I managed to solve it and get the pull request button. Previously was because I have not pushed each branch to my repo, so there is no button. Sorry for bothering
