### ISSUE TITLE
Overly strict repository naming rules

### ISSUE THREAD

**Issue by alcen** [nus-cs2103-AY1920S2/forum#36]
I just wanted to know why the repository name for the individual project is restricted to `duke`. It seems like a simple change to allow for the analysis tool to handle a variety of repository names (I could be wrong, but it seems to be linked to this .csv file here: https://github.com/nus-cs2103-AY1920S2/ip-dashboard/blob/master/configs/repo-config.csv).

Doing so would allow us greater customisation of the application, which was heavily promoted from the start of the project (in the individual project tasks allocated for Week 2, Level 1 specifically says that changing the chatbot name is strongly encouraged). Also, the CS2103T feedback bot already does not limit itself to a certain repository name. 

Some context: I had a different repository name since Week 1 and was only asked to change it recently, which was quite inconvenient for me - https://github.com/alcen/duke/issues/3

**Comment by okkhoy** [comment]
I understand your concern. However, we have good reasons to be a bit rigid.

The configurations are generated using a script (imaging setting the config for 210 students, which is simply not feasible + may be prone to errors). Hence we fixed certain parameters and one of them is the repo name. Hence, expect the repo names to be the same. 
The same applies to the team project where we want the repo name to be `main`.

WRT feedback bot: the bot uses Github API to track the forks of `duke`. As long as your repo is a fork, the bot can work. 

It would be a good idea to merge the logic between the two (currently) independent scripts. We plan to do it soon, but at the moment, they are independent of each other.

**Comment by alcen** [comment]
Ok, I see. Thank you for the detailed explanation!
