### ISSUE TITLE
Java version for project

### ISSUE THREAD

**Issue by lharland** [nus-cs2103-AY1920S2/forum#37]
Which version of java do i publish the jar file with?

**Comment by zhuhanming** [comment]
Should be Java 11, as found under [Week 1 Admin Info](https://nus-cs2103-ay1920s2.github.io/website/schedule/week1/admin.html#2-set-up-the-tools-before-the-lecture).

**Comment by lharland** [comment]
Ok thanks for the response, I figured java 11 to be the ideal version too
