### ISSUE TITLE
Duke works on IntelliJ but not on command prompt

### ISSUE THREAD

**Issue by gyant6** [nus-cs2103-AY1920S2/forum#38]
When I run Duke using this filepath "data/tasks.txt", the application is unable to find the txt document, I get a FileNotFoundException. But I can run Duke from command prompt and still save to the txt document. 

When it is ran using "src/main/java/duke/data/tasks.txt", I am able to run the application from IntelliJ but not from command prompt. 

Could this have to do with my project structure? Have been stuck at this for 2 weeks already D:

**Comment by zhuhanming** [comment]
Hi @gyant6, I took a quick look through your implementation for storage - it seems that there is some hardcoding involved in terms of your exact storage location, and the location of your save file may differ based on whether you successfully loaded the in the `load()` method (i.e. if the file is located, the given `filePath` is used, but if the file isn't, you hardcoded a savefile location, which may not be the same as `filePath`.)

I think the best way is to simply have a single source of truth - the `filePath` passed into the Storage instance. Perhaps when you fail to locate the save file (which may be relative to wherever the program is being run), what you can do is to `mkdir()` or `mkdirs()` using the `filePath` given to create the required folder(s), then let the user know that the loading failed, and will be writing to a new save file from now on. This would allow your program to run and save regardless of where it is located. The `filePath` to pass in would then ideally be a relative path, e.g. `data/tasks.txt`. The file writing should work so long the required folder(s) exists.

**Comment by CornCobs** [comment]
How are you running the program on command line? Are you running it after packaging it as a jar? Or cd-ing into the compiled classes directory and running the Main class? In general, the file paths in Java will be relative to where you run your program from, so make sure the directory you're running in has a data/ folder

**Comment by gyant6** [comment]
> Hi @gyant6, I took a quick look through your implementation for storage - it seems that there is some hardcoding involved in terms of your exact storage location, and the location of your save file may differ based on whether you successfully loaded the in the `load()` method (i.e. if the file is located, the given `filePath` is used, but if the file isn't, you hardcoded a savefile location, which may not be the same as `filePath`.)
> 
> I think the best way is to simply have a single source of truth - the `filePath` passed into the Storage instance. Perhaps when you fail to locate the save file (which may be relative to wherever the program is being run), what you can do is to `mkdir()` or `mkdirs()` using the `filePath` given to create the required folder(s), then let the user know that the loading failed, and will be writing to a new save file from now on. This would allow your program to run and save regardless of where it is located. The `filePath` to pass in would then ideally be a relative path, e.g. `data/tasks.txt`. The file writing should work so long the required folder(s) exists.

Sorry that line was to debug to see how the File.createNewFile() function worked. Updated the line to use relative filepaths instead of the hardcoded one. Still does not work.

**Comment by zhuhanming** [comment]
Hi @gyant6, perhaps it’s because the folder(s) that contains the save file do not exist in the current user directory that you’re running the program from. You can try `mkdirs()` to create the folders required first. You can find out more from this [stackoverflow post](https://stackoverflow.com/questions/6666303/javas-createnewfile-will-it-also-create-directories).

**Comment by mario7lorenzo** [comment]
Hi there! I think I just share my directory structure. So, my Reader and Writer classes are stored inside a package `util` in `/src/main/java/duke/util` directory. However, my `data` directory is stored in the root directory. Therefore, in my reader and writer, I just use `./data/filename.txt` as the file path. I believe when using gradle, the directories are relative to the root directory, which is the first `duke` directory name. Try to mimic the structure first, and let me know if there is still the issue!

**Comment by gyant6** [comment]
My problem was that the `data` directory was not stored in the root directory. My bad. Thanks all for helping! @mario7lorenzo @zhuhanming
