### ISSUE TITLE
Checkstyle error: AvoidEscapedUnicodeCharacters

### ISSUE THREAD

**Issue by Yiping-Z** [nus-cs2103-AY1920S2/forum#40]
I used "\u2718" and "\u2713" to represent cross and tick, however, running gradle build with checkstyle enabled gives me checkstyle error: AvoidEscapedUnicodeCharacters. How to solve this issue?

**Comment by zhuhanming** [comment]
To avoid this issue, comment at the end of the line what the escaped unicode character means!

You can actually see this from the `checkstyle.xml`
```
// Line 41
<module name="AvoidEscapedUnicodeCharacters">
    // ...
    <property name="allowByTailComment" value="true"/>
    // ...
</module>
```

**Comment by Yiping-Z** [comment]
Thanks!
