### ISSUE TITLE
Importance of user.email

### ISSUE THREAD

**Issue by shenghaoc** [nus-cs2103-AY1920S2/forum#41]
Can I confirm that only the Git user.name matters to the tools that analyze our code and not the user.email?
I followed the instructions for Week 2 and set user.name but not user.email so my commits are not associated with my GitHub account.

**Comment by okkhoy** [comment]
Please check https://nus-cs2103-ay1920s2.github.io/ip-dashboard/#sort=groupTitle&groupSelect=groupByAuthors if your code detected is correct? If so, then you are good, no need to worry.

If I remember correctly, reposense needs only the `user.name` and not the email

**Comment by shenghaoc** [comment]
Thank you!
