### ISSUE TITLE
Images and other markdown effects not showing up in website

### ISSUE THREAD

**Issue by raniceyue** [nus-cs2103-AY1920S2/forum#42]
Hello, I am writing my user guide now. I have added some images to the user guide. Unfortunately, the images are not showing up in the page for the user guide. Has anyone else faced this problem? Also, are we even supposed to add images in our user guides?

**Comment by lohszeying** [comment]
Apparently, the user guide is updated in `http://{your username}.github.io/duke/`, as the CS2103T website says "Go to http://{your username}.github.io/duke/ to view the user guide of your product."

**Comment by raniceyue** [comment]
> Apparently, the user guide is updated in `http://{your username}.github.io/duke/`, as the CS2103T website says "Go to http://{your username}.github.io/duke/ to view the user guide of your product."

Yeap I'm viewing my user guide from the website, but all the images I added can be seen through the readme in the repo but can't be seen on the site.

**Comment by limdylan** [comment]
Try `![](images/todoDemo.png)` instead of `![](/docs/images/todoDemo.png/)`?

**Comment by mario7lorenzo** [comment]
hi! a working attempt from me is to use `<img src="Ui.png">` instead. and mak the `src` parameter as a file path relative to the `README.md` file.

**Comment by raniceyue** [comment]
> hi! a working attempt from me is to use `<img src="Ui.png">` instead. and mak the `src` parameter as a file path relative to the `README.md` file.

Hello! Thank you so much! This worked for me :)
