### ISSUE TITLE
Created jar file on Mac, couldn't run jar file on Windows

### ISSUE THREAD

**Issue by lohszeying** [nus-cs2103-AY1920S2/forum#43]
Hi! I've successfully created the jar file on mac and ran it on mac with terminal command `java -jar duke.jar`. I used `duke [shadowJar]` to build the jar file.
However, I could not run the jar file on my Windows. I've tried to update my Java on Windows to version 13.0.2. When I ran java -jar duke.jar on Windows cmd, it says "Error: JavaFX runtime components are missing, and are required to run this application". Is this error supposed to appear for an isolated PC (PC not running any school related project, for personal use) when it tries to run Duke jar? Or is jar file supposed to work for any PC and I am supposed to somehow put in JavaFX into the jar?

Thanks!

**Comment by okkhoy** [comment]
A few things:
1. if you are using Java 13, unfortunately, you need to downgrade to Java 11; the rest of the class uses Java 11, so compatibility issues will arise.
2. update your build.gradle file as per the instructions here: https://github.com/se-edu/duke/blob/master/tutorials/javaFxTutorialPart1.md
3. I am not sure what you meant by `duke [shadowjar]` you need to build the JAR using `gradelw shadowJar` to include the runtime components for all platforms (provided you updated the build file as per (2) above.

**Comment by lohszeying** [comment]
Hi! I'm using Java 11 on my Mac (Duke project PC), and Java 13 on my Windows (for personal use). Will that be ok in trying to run .jar file on my Windows?

**Comment by okkhoy** [comment]
No personal experience with Java 13, but Java should be generally backward compatible. Can anyone else with experience update us here, please?

**Comment by mario7lorenzo** [comment]
hi, I suspect it is regarding to the dependency in your javafx file? You need to make it cross-platform by adding dependencies in the `build.gradle` file. You can refer to the second point of what prof Akshay said.

**Comment by lohszeying** [comment]
My `build.gradle` have included the dependencies as stated in prof Akshay's second point. I've also tried to downgrade my Windows Java to 11.0.2. However, I got this error:
![2020-02-16 (8)](https://user-images.githubusercontent.com/34441049/74600339-1b033680-50cb-11ea-9e58-db85b325c43e.png)

**Comment by lohszeying** [comment]
My `build.gradle` is:
```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
    id 'org.openjfx.javafxplugin' version '0.0.7'
}

checkstyle {
    toolVersion = '8.23'
}

group 'seedu.duke'
version '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    // Change this to your main class.
    mainClassName = "Launcher"
}

run {
    standardInput = System.in
}

shadowJar {
    archiveBaseName = "duke"
    archiveVersion = "0.1.3"
    archiveClassifier = null
    archiveAppendix = null
}

jar {
  manifest {
   attributes 'Main-Class': 'Launcher'
  }
}
```

**Comment by okkhoy** [comment]
Try removing this:
```
javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```
from your `build.gradle`.

Build your fat jar using `gradlew shadowJar` and let us know what happens.

The "no suitable pipeline found" seems like a common case of not including the required library.

**Comment by lohszeying** [comment]
Thank you! Now both my Windows PC and Mac can open .jar file!
Though there is another thing, when I try to run the .jar file in cmd & terminal using the command `java -jar`, there is this message. (same message in both Windows and Mac). Can this be ignored?
![2020-02-16 (10)](https://user-images.githubusercontent.com/34441049/74600681-cadaa300-50cf-11ea-863b-53dd008da2d1.png)

**Comment by okkhoy** [comment]
Great!!

I suspect there is a minor version mismatch in the JRE you have vs the JDK. It should generally be fine to ignore it; I haven't come across anything catastrophic due to this warning.

**Comment by lohszeying** [comment]
Prof, can I also confirm that by Java 11, do you mean it is java version 11 when running java -version in terminal/cmd? Like this "11.0.2" means it's also under Java 11?
<img width="572" alt="Screenshot 2020-02-16 at 3 44 44 PM" src="https://user-images.githubusercontent.com/34441049/74600954-543fa480-50d3-11ea-8878-64424dee3e72.png">

**Comment by okkhoy** [comment]
Yes, Java 11.x.x are all Java 11 🙂

**Comment by lohszeying** [comment]
> Yes, Java 11.x.x are all Java 11 🙂

Thank you!
