### ISSUE TITLE
Duke JAR file unable to find duke.txt file

### ISSUE THREAD

**Issue by raniceyue** [nus-cs2103-AY1920S2/forum#45]
Hello, I have just created my Duke JAR file. Unfortunately, the method I used to get the path to my `duke.txt` file does not work anymore. My `duke.txt` file is stored in a data file that is stored in the root of the repo, i.e. `/data/duke.txt`

I was just wondering, is there any way I am able to get the path to the file within the JAR executable? Or must I have to make it such that Duke creates a new file outside the JAR executable?

**Comment by mario7lorenzo** [comment]
Hi! May I know how do you get the path? And how do you tackle when there is no file exists

**Comment by okkhoy** [comment]
Make Duke create a new file outside of the JAR. The storage file need not be inside the JAR.
