### ISSUE TITLE
tp Week 5 setting up auto publishing of docs

### ISSUE THREAD

**Issue by raniceyue** [nus-cs2103-AY1920S2/forum#47]
Hello 

I have followed the tutorial [here](https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/docs/UsingTravis.adoc) on setting up Travis for auto-publishing of the user guide, for some reason, when I try to access my [team's link ](https://ay1920s2-cs2103-f09-4.github.io/addressbook-level3/index.html) according to the tutorial, the page shows a 404 instead of the README.md.

I am not sure if I missed a step, but I followed everything exactly as in the tutorial for both my personal fork and the fork in my team repo, and the link still leads to a 404.

**Comment by okkhoy** [comment]
There you go https://ay1920s2-cs2103-f09-4.github.io/main/index.html 😃

**Comment by raniceyue** [comment]
oh my goodness haha I really deadass thought there was something wrong because main =/= addressbook-level3 and I thought we had to follow the link exactly ~_~
