### ISSUE TITLE
Unable to run Jarfile

### ISSUE THREAD

**Issue by Weiichengg** [nus-cs2103-AY1920S2/forum#51]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

```java

I am able to build and run the jarfile normally in intellij.
However, when this error shows up when I try to run the jarfile.
"Error: Could not find or load main class duke.Launcher
Caused by: java.lang.ClassNotFoundException: duke.Launcher"

I tried to open the jarfile from a folder but it is unable to run too.
I have asked my groupmates to run the jarfile, but they are unable to run it too.
Kindly assist. Thanks!
```

**Comment by okkhoy** [comment]
I want to add: Please refrain from putting up screenshots; it is better to copypaste the code snippet/error messages so that if any of us want to try out, we can copypaste your code/build instructions.

**Comment by Weiichengg** [comment]
I realised that is something wrong with my initial relative path. Thank you for your help!
