### ISSUE TITLE
Tutorial Week 6 queries

### ISSUE THREAD

**Issue by eugenetyc** [nus-cs2103-AY1920S2/forum#54]
```
Tutorial 3 - Adding a new Command
If you are an experienced programmer, you can add a different command than the one given in the tutorial.
Submission: Do your changes in a branch named tutorial-adding-command, push to your fork, and create a PR from your fork to your team's repo.
```
Based on this week's task on the schedule website, once we are done with the 3 tutorials, are we supposed to create pull requests for both branches `tutorial-removing-field` and `tutorial-adding-command` or do we simply to create a pull request from the `master branch of our own fork`, **which does NOT contain these changes**?

Note: This is with respect to creating PRs to the Team's Repo.

Cheers!

**Comment by okkhoy** [comment]
Err, I missed this query earlier. Sorry! You need to create 2 PRs, one for each tutorial, from the branch

**Comment by eugenetyc** [comment]
Ok, thank you Prof!
