### ISSUE TITLE
Call backs in self invocation

### ISSUE THREAD

**Issue by shenghaoc** [nus-cs2103-AY1920S2/forum#56]
Under self invocation, the examples include a variation in which a method of an object does not call another of its own methods directly.
Instead, it does so indirectly through a call back by first calling a method of another object.
May I confirm that as long as another method of an object is called before a method returns, it is considered self-invocation?

**Comment by eugenetyc** [comment]
Hi,
In my opinion, as long as the control returns to an incompleted task concerning the original Object, it is self-invocation.

Good point raised.

**Comment by okkhoy** [comment]
Yes, you can consider the given scenario to be a self-invocation. However, do note and be aware that the mechanisms are entirely different.

**Comment by shenghaoc** [comment]
Thank you!
