### ISSUE TITLE
A-TextUITesting

### ISSUE THREAD

**Issue by SHAUNGOH97** [nus-cs2103-AY1920S2/forum#6]
Hi, for the A-TextUITesting component of Duke, what is the objective of this task?
Am I suppose to write out a full EXPECTED.txt script to test my Duke programme? Or am I just suppose to follow the tutorial and just create the files and fill in the classpaths. 
I am abit confused on the objective of this task.

Thanks in advance:)

**Comment by mario7lorenzo** [comment]
Hi there! The extension is intended for you to simply semi-automate the testing of your project. If you really want to use the method, you need to write the whole expected output in EXPECTED.txt . Other than that, the test is meant to like "abstract" the test and just indicates whether the code passes the test or not. If not, it will indicate where is the line difference, thus make your debugging process easier!

**Comment by okkhoy** [comment]
The objective is the understand how to automate regression tests, when you have access _only_ to the external behavior of the program (in this case, via the commands). 

Yes, the right way to do this is to write out the `EXPECTED.txt` to define your expectation when the command has run; When you run the command and the actual output doesn't match the expected output, you encountered a bug.
At this stage, you fix either the code or the test (as the case may be).

**Comment by SHAUNGOH97** [comment]
Thanks!
I think I understand the objective now.
