### ISSUE TITLE
asciidoctor: WARNING: invalid style for fenced_code block: source

### ISSUE THREAD

**Issue by umaikaze** [nus-cs2103-AY1920S2/forum#63]
![image](https://user-images.githubusercontent.com/58588107/75626500-f0ed6080-5c02-11ea-9a30-6689133b9bc7.png)
As seen in the screenshot, this error shows up and the main window would not appear if I run the project with IntelliJ. However, it works if I just use 'gradlew run'. The project was freshly cloned from the AB3 repo, may I know what caused the difference?
My current project structure is as such:
![image](https://user-images.githubusercontent.com/58588107/75626564-69542180-5c03-11ea-9f6b-3c4b8505397f.png)
![image](https://user-images.githubusercontent.com/58588107/75626566-7244f300-5c03-11ea-9199-e716110659f8.png)

**Comment by okkhoy** [comment]
@j-lum would you be able to answer this?

**Comment by okkhoy** [comment]
Actually, when I checked with the semester fork, the build doesn't fail and the pages are generated. So, @umaikaze is it really a problem?

**Comment by j-lum** [comment]
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

Have you tried using `----` to delimit a block instead?

**Comment by umaikaze** [comment]
> Actually, when I checked with the semester fork, the build doesn't fail and the pages are generated. So, @umaikaze is it really a problem?

Oh, sorry, I later realized I am able to run AB3 with 'gradlew run' but couldn't figure out how to change the issue label to 'question' haha.

**Comment by umaikaze** [comment]
> https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code
> 
> Have you tried using `----` to delimit a block instead?

Thank you! This resolved my issue!
