### ISSUE TITLE
Travis-CI rebuild pages reverts changes

### ISSUE THREAD

**Issue by teo-jun-xiong** [nus-cs2103-AY1920S2/forum#65]
After editing html files in ```gh-pages``` to remove the headers and references to AddressBook-Level3, a commit to the ```master``` triggered Travis to Rebuild pages. This seemed to revert the changes made to the html files committed previously, why is that so? Is directly editing the html in ```gh-pages``` the correct why to go about it?

Thanks!

**Comment by okkhoy** [comment]
You are not supposed to edit the html pages directly. Make the necessary changes in the adoc files and push the changes to your master branch. Auto-publishing will take care of generating the html pages.

Edit: 
You may want to look at: https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/docs/Documentation.adoc#6-site-wide-documentation-settings

**Comment by teo-jun-xiong** [comment]
Ah that makes more sense. Alright, will take a look at it. Thank you!
