### ISSUE TITLE
Travis build failing even after reverting changes

### ISSUE THREAD

**Issue by BryanYap972** [nus-cs2103-AY1920S2/forum#68]
<img width="984" alt="Screenshot 2020-03-05 at 9 51 40 PM" src="https://user-images.githubusercontent.com/52154266/75988215-3031ef00-5f2c-11ea-8164-d266608143e8.png">

Changed some settings in _header.html.slim file. The pull request to merge changes to master passed travis CI. However, after merging subsequent builds started failing due to the same errors as shown in the screenshot. Does anyone know how to resolve this? We have tried reverting the changes but the pull request to revert fails the travis CI.

**Comment by BryanYap972** [comment]
Running ./gradlew clean asciidoctor --stacktrace shows build successful with no warning messages.

**Comment by okkhoy** [comment]
@j-lum any idea?

**Comment by AaronCQL** [comment]
My team had a very similar problem and we managed to resolve it by following [this link](https://docs.travis-ci.com/user/caching/#clearing-caches). Basically, we had to clear all the stored cache in Travis and just rerun the failed builds again.

**Comment by BryanYap972** [comment]
> My team had a very similar problem and we managed to resolve it by following [this link](https://docs.travis-ci.com/user/caching/#clearing-caches). Basically, we had to clear all the stored cache in Travis and just rerun the failed builds again.

That worked. Thanks so much!
