### ISSUE TITLE
Coveralls source not found issue.

### ISSUE THREAD

**Issue by sheexiong** [nus-cs2103-AY1920S2/forum#69]
When i try to check uncovered line in Coveralls, it shows the source not found an error instead of the file.

[coveralls link](https://coveralls.io/builds/29178840/source?filename=file%3A%2Fhome%2Ftravis%2Fbuild%2FAY1920S2-CS2103T-W13-1%2Fmain%2Fsrc%2Fmain%2Fjava%2Fseedu%2Faddress%2Fstorage%2FJsonSerializableAddressBook.java)

**Comment by okkhoy** [comment]
@j-lum  would you know what is happening here?

**Comment by j-lum** [comment]
I see that they have resolved the issue. @sheexiong do you want to share how your team managed to do it for other the benefit of other teams?

**Comment by sheexiong** [comment]
@j-lum We still unable to solve this issue, here is a screenshot for the source not available issue.
![image](https://user-images.githubusercontent.com/27266855/76536665-9e8c2980-64b7-11ea-80f5-cc5549c528ef.png)

**Comment by j-lum** [comment]
![image](https://user-images.githubusercontent.com/22460123/76559418-19fed280-64da-11ea-995b-83dfbc0fbc34.png)
Set your git repo root directory to file:/home/travis/build/.../main as per instructions in the error message.

**Comment by sheexiong** [comment]
@j-lum Thanks for the help, I managed to solve the issue by add `file:/home/travis/build/AY1920S2-CS2103T-W13-1/main/` as the git repo root directory.
