### ISSUE TITLE
Requesting Permission to use a Third-Party Library

### ISSUE THREAD

**Issue by gohkh** [nus-cs2103-AY1920S2/forum#77]
## Library

[Apache Commons Math 3.6.1](https://commons.apache.org/proper/commons-math/)

## Purpose

My team's app contains a recipe database, and we would like to use the library to support fractions in ingredient quantities.

## License

[Apache License](https://github.com/apache/commons-math/blob/master/LICENSE.txt)

**Comment by okkhoy** [comment]
Approved 👍
