### ISSUE TITLE
Question on Commit Guidelines

### ISSUE THREAD

**Issue by zhuhanming** [nus-cs2103-AY1920S2/forum#8]
Hi, may I ask if there are any guidelines for commit messages in this module? I remember this being briefly covered during last week's lecture, with the example given being "add [feature]"; however, I've been unable to find any information about this on the website.

I am currently referring to Angular's commit message guidelines as found [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines), which I feel is more detailed, and allows people to look through the commit history and quickly understand the changes going on. Is this alright?

**Comment by mario7lorenzo** [comment]
Hi! If i remember correctly, there is only a few mentioned in the lectures, but the one that was emphasized during the lecture is the convention when you commit new feature. You use “add something” as the commit message. Maybe other people or prof Akshay can give more regarding to this, especially if the convention used throughout cs2103 is different :)

**Comment by okkhoy** [comment]
Ideally, doing something like the Angular commit messages is good. You can see a sample from the se-edu org (which hosts the NUS OSS projects) [here](https://github.com/se-edu/addressbook-level3/commit/f77cfc993419caccea2594956795f1f565619442). The sample varies from what @zhuhanming has linked, but has all the necessary stuff.

We do understand that it is quite some work to write such detailed comments. Hence, we don't mandate it in the project. What we do insist on is:
1. following the convention in terms of the tone of the commit message.
2. writing succinct commit messages/headers that convey the change immediately

**Comment by zhuhanming** [comment]
Thanks prof @okkhoy and @mario7lorenzo! Thanks prof for covering this in Friday's lecture as well!
