### ISSUE TITLE
RepoSense / GitHub Contributions page not picking up commits

### ISSUE THREAD

**Issue by wxwxwxwx9** [nus-cs2103-AY1920S2/forum#85]
**PROBLEM**

What happened was that my Sourcetree actually modified my global Git configuration, as the checkbox was ticked as you can see in the screenshot below. 

I believe I might have accidentally ticked the box and modified the setting in the past, not aware that it would result in the current problem. 

I have since unchecked the box. 

![Screen Shot 2020-03-20 at 7 00 13 PM](https://user-images.githubusercontent.com/37920115/77219596-613c3180-6b72-11ea-8a6a-aec5740e51b9.png)

This resulted in whatever commits that I pushed to the main repository of our project to be recorded under the name “weixiang”. 

Usually when you hover over and click the name under a commit, you would be redirected to that person’s GitHub profile. 

However, in this case, name “weixiang”  was not linked to my GitHub username, “wxwxwxwx9”. 

Thus, the name (“weixiang”) does not have an active link that redirects the user to the appropriate profile (“wxwxwxwx9”) (the name was just a static word). 

Furthermore, my username was not found under the contributions page for our team repository. 

**ATTEMPTED SOLUTION**

From what I found out, it seems that each commit on GitHub is tied to an email address. 

Referring to the same screenshot above, I noticed that the email address that was tagged along with the name “weixiang” was my school email address, weixiangong96@u.nus.edu.

Thus, I figured that I simply have to add my school email address to my GitHub profile (“wxwxwxwx9”) so that I can “claim” the commits on GitHub. 

I did this on my GitHub account setting page. 

It worked — all the commits which previously were under the name “weixiang” are now under “wxwxwxwx9”, which is what we wanted. 

**CURRENT SITUATION**

I made the above changes on Friday at around 2pm. 

From what I’ve read, it seems that it would take up to 24 hours for the contributions page to reflect my commits, after the changes I made. 

I believed that it would be the same for RepoSense as well. 

However, it is now well over 24 hours — RepoSense and the contributions page of our team repository are still not reflecting my commits. 

Can I get some advice on how I can rectify the issue? 

Thank you so much for your help!

**Comment by okkhoy** [comment]
1. The latest reposense run was Yesterday ~5 pm (Scroll down to the end of the page in tp-Dashboard, you can see the lastest run time). So if your changes were made after that, it may not be reflected.
2. Reposense depends on the actual commits you make. 
  - You can follow the instruction and create a PR to update the config to add the addition `user.name`. 
  - Instructions for that here: https://nus-cs2103-ay1920s2.github.io/website/admin/tools.html#tool-used-reposense-for-analyzing-code-authorship (check the box "For Simple Cases")

Tag: @Tejas2805 If additional help necessary please ping (bug? 😉)  our tutor, Tejas.

**Comment by wxwxwxwx9** [comment]
Hi Prof., 

Thank you for the advice! I have submitted the pull request for the tp-dashboard to update my user.name. 

My major worry is that the commits that I have made are **not showing up on the "contributions page"** on my GitHub team repository even after a week. They are, however, present in the "commits page" and the relevant pull requests. 

Could there be some underlying issues? 

Here is my team repo link for your reference: https://github.com/AY1920S2-CS2103T-F10-2/main/graphs/contributors

**Comment by okkhoy** [comment]
I suspect it has to do with your user.name and user.email setting. From what I can recollect, GitHub recognizes the user.email field. Try to use the same email address that you have used to create your GitHub account. (this info is at least 2 years old. so if things have changed, please don't hold me to this 😂 ) However, older commits won't be shown.
You can also try to add your user.email to your Github account, but not sure of the effect. This is a random thought.
As long as user.name is set properly, reposense should be able to pick it up.

I will merge the PR on tp dashboard page.
