### ISSUE TITLE
Why are instance variables of Person, Phone, Email, etc declared public/private final?

### ISSUE THREAD

**Issue by sharadhr** [nus-cs2103-AY1920S2/forum#86]
Question is in the title. As my team is morphing the code-base, we have encountered this design pattern over and over, and don't fully understand the motivation for it. 

In [`Person.java`](https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/src/main/java/seedu/address/model/person/Person.java), for instance, we have `private final` instance variables `address`, `email`, `phone`, etc, whereas in [`Address.java`](https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/src/main/java/seedu/address/model/person/Address.java), the instance variable is `public final`. 

Especially in the latter case, we have a pattern that appears to go headlong against the oft-repeated OOP pattern of 'keep instance variables private, and change/access them through accessor methods only'. 

Could we have some notes from the developer team about your thought-process, motivations and any other driving factors behind this design pattern of `final`-ising instance variables?

____

Another strange thing we've found is the `VALIDATION_REGEX` static final variable for some `String`s; why not use [`String#isBlank()`](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/String.html#isBlank()) instead?

**Comment by okkhoy** [comment]
Some of the variables were made public for convenience's sake. For some, there is no particular reason (it was what the developer decided)
You can view the blame view for the file to check if there is a reason. For instance, in this case, the team decided to make Person immutable.
![image](https://user-images.githubusercontent.com/1023494/77243509-c876e600-6c45-11ea-8918-c4ed86078f64.png)

WRT validation, I guess it was for consistency, even though no other validation is happening at the moment.
