### ISSUE TITLE
Request to use javax.measure reference implementation and JMetro JavaFX theme

### ISSUE THREAD

**Issue by sharadhr** [nus-cs2103-AY1920S2/forum#95]
## Library

[Indriya](https://github.com/unitsofmeasurement/indriya), `javax.measure` reference implementation (JSR-385)

## Purpose

Using and converting between common household and culinary units (kg, l, ml, tsp, tbsp, etc). 

## License

[BSD3](https://github.com/unitsofmeasurement/indriya/blob/master/LICENSE)

## Library

[JMetro](https://pixelduke.com/java-javafx-theme-jmetro/)

## Purpose

UI improvements, and adhering to a nicer UI theme

## License

BSD3.

**Comment by okkhoy** [comment]
Approved, both 👍
